import { Inknut_Antiqua, Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../../context/auth";
import { Providers } from "./provider";
// const inter = Inter({ subsets: ["latin"] });
const inknut = Inknut_Antiqua({ weight: "500" ,subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <AuthProvider>
          <Providers>
            {children}
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
